// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-contact.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_default = defineTool({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Returns Om Shala's public contact details: email, WhatsApp, and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      brand: "Om Shala",
      email: "omshala.official@gmail.com",
      whatsapp: "+91 74003 61681",
      location: "Bandra West, Mumbai"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/get-about.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_about_default = defineTool2({
  name: "get_about_shrutika",
  title: "About Shrutika",
  description: "Returns a short biography of Shrutika, the founder and guide behind Om Shala.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const bio = {
      name: "Shrutika",
      role: "Meditation Teacher & Indian Classical Singer",
      practice: "Nada Yoga \u2014 the yoga of sound and music",
      instruments: ["Crystal Singing Bowls", "Voice"],
      supports: ["Breathwork", "Guided Relaxation"],
      philosophy: "Pure sound pulls you inward and brings deep relaxation. In this state, the body is guided back to its natural rhythm and the mind returns to centre.",
      approach: "Intuitive, somatic \u2014 profound relaxation as the gateway to the inner life."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(bio, null, 2) }],
      structuredContent: bio
    };
  }
});

// src/lib/mcp/tools/list-experiences.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var experiences = {
  corporate: {
    audience: "Corporate organisations",
    offerings: [
      "Employee wellbeing sessions",
      "Leadership retreats",
      "Wellness initiatives",
      "Online and in-person sound baths"
    ],
    format: "Guided sound healing with Crystal Singing Bowls and voice, supported by breathwork and guided relaxation."
  },
  private: {
    audience: "Individuals and small groups",
    occasions: [
      "Weddings",
      "Birthdays",
      "Anniversaries",
      "Intimate gatherings",
      "Personal retreats"
    ],
    format: "Bespoke sound healing experiences designed around the occasion and space."
  }
};
var list_experiences_default = defineTool3({
  name: "list_experiences",
  title: "List experiences",
  description: "Lists Om Shala's two experience tracks (corporate and private) with audience and offerings. Pass a track to get just that one.",
  inputSchema: {
    track: z.enum(["corporate", "private", "all"]).optional().describe("Which track to return. Defaults to 'all'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ track }) => {
    const key = track ?? "all";
    const result = key === "all" ? experiences : { [key]: experiences[key] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "om-shala-mcp",
  title: "Om Shala MCP",
  version: "0.1.0",
  instructions: "Tools for Om Shala \u2014 a sound-healing practice by Shrutika. Use these tools to look up contact details, learn about the guide, and list corporate/private experience tracks.",
  tools: [get_contact_default, get_about_default, list_experiences_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
